export default interface State {
  template?: string
  time?: string
  relative_time?: number
  add_time?: number
  opacity?: number
  storyboard_opacity?: number
  ui_opacity?: number
  scanline_opacity?: number
  background_dim?: number
  note_opacity_multiplier?: number
  scanline_color?: string
  NoteFillColor?: string[]
  note_ring_color?: string
  override_scanline_pos?: boolean
  scanline_pos?: number
  perspective?: boolean
  size?: number
  fov?: number
  x?: number
  y?: number
  rot_x?: number
  rot_y?: number
  rot_z?: number
  vignette?: boolean
  vignette_intensity?: number
  vignette_color?: string
  vignette_start?: number
  vignette_end?: number
  chromatic?: boolean
  chromatic_intensity?: number
  chromatic_start?: number
  chromatic_end?: number
  chromatical?: boolean
  chromatical_fade?: number
  chomatical_intensity?: number
  chromatical_speed?: number
  bloom?: boolean
  bloom_intensity?: number
  radial_blur?: boolean
  radial_blur_intensity?: number
  color_adjustment?: boolean
  brightness?: number
  saturation?: number
  contrast?: number
  color_filter?: boolean
  color_filter_color?: string
  gray_scale?: boolean
  gray_scale_intensity?: number
  noise?: boolean
  noise_intensity?: number
  sepia?: boolean
  sepia_intensity?: number
  dream?: boolean
  dream_intensity?: number
  fisheye?: boolean
  fisheye_intensity?: number
  shockwave?: boolean
  shockwave_speed?: number
  focus?: boolean
  focus_size?: number
  focus_color?: string
  focus_speed?: number
  focus_intensity?: number
  glitch?: boolean
  glitch_intensity?: number
  arcade?: boolean
  arcade_intensity?: number
  arcade_interference_size?: number
  arcade_interference_speed?: number
  ArcadeContrast?: number
  Tape?: boolean
}
